#!/bin/bash

set -e 

echo "Uncomment net.ipv4.ip_forward and set to 1"
sleep 1

sudoedit /etc/sysctl.conf

sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F
sudo iptables -t mangle -F
sudo iptables -F
sudo iptables -X

# Assuming the internet interface is wlan0
# https://serverfault.com/questions/431593/iptables-forwarding-between-two-interface
sudo iptables -A FORWARD -i eth0 -o wlan0 -j ACCEPT
sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE


sudo apt install iptables-persistent -y
sudo netfilter-persistent save
