#!/bin/bash

set -e 

echo "Uncomment net.ipv4.ip_forward and set to 1"
sleep 1

sudoedit /etc/sysctl.conf

INTERFACE_A='eth0'
INTERFACE_B='wlan0' # Internet-facing
echo "Forwarding between interfaces $INTERFACE_A (local) and $INTERFACE_B.. (internet)"

sudo iptables -P INPUT ACCEPT
sudo iptables -P FORWARD ACCEPT
sudo iptables -P OUTPUT ACCEPT
sudo iptables -t nat -F
sudo iptables -t mangle -F
sudo iptables -F
sudo iptables -X

# https://serverfault.com/questions/431593/iptables-forwarding-between-two-interface
sudo iptables -A FORWARD -i $INTERFACE_A -o $INTERFACE_B -j ACCEPT
sudo iptables -A FORWARD -i $INTERFACE_B -o $INTERFACE_A -j ACCEPT
sudo iptables -t nat -A POSTROUTING -o $INTERFACE_B -j MASQUERADE


sudo apt install iptables-persistent -y
sudo netfilter-persistent save
