#!/bin/bash

set -e

sudo touch /etc/netplan/01-config.yaml
echo "Note that config files must be .yaml, not .yml"
echo "Copying template netplan config.yaml to clipboard."
echo "Paste it in the opened file!"
sleep 1

echo "
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses: 
        - 10.233.0.2/24
      gateway4:
        - 10.233.0.1
      nameservers:
        addresses: [10.233.0.1]
  wifis:
    wlan0:
      dhcp4: true
      access-points:
        "SSID_HERE":
          password: "PASSWD_HERE"
" | xclip -sel c

sudo vim /etc/netplan/01-config.yaml

sudo netplan generate
sudo netplan apply
