#!/bin/bash
set -e 
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
$SCRIPT_DIR/dotfiles-install # Do this once first for initialization purposes.
DOTFILES_DIR=$SCRIPT_DIR/../dotfiles

sudo apt update 

sudo apt install cmake -y
sudo apt install curl wget -y
sudo apt install git -y
sudo apt install inotify-tools -y
sudo apt install picocom -y
sudo apt install chrony -y 
sudo apt install xclip -y
sudo apt install python3 python3-pip -y 
sudo apt install exuberant-ctags -y
sudo apt install ipython3 -y
sudo apt install openssh-server -y
sudo apt install software-properties-common -y
sudo apt install llvm-7 clang-7 libclang-7-dev -y
sudo apt install clang -y
sudo apt install build-essential -y
sudo apt install pv -y
sudo apt install python3-setuptools -y
sudo apt install htop -y
sudo apt install time -y
sudo apt install lsof -y

pip3 install jupyterlab
pip3 install pdbpp

sudo apt update 

# Install CGDB
sudo apt install texinfo flex libreadline-dev -y
git clone git://github.com/cgdb/cgdb.git $HOME/cgdb
cd $HOME/cgdb
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
cd $HOME
rm -r $HOME/cgdb


# Install ripgrep
curl -L https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep_11.0.2_amd64.deb -o $HOME/rg.deb
sudo dpkg -i $HOME/rg.deb
rm $HOME/rg.deb

# Install FZF
[ -d "$HOME/.fzf" ] && yes | rm -r $HOME/.fzf 
git clone --depth 1 https://github.com/junegunn/fzf.git $HOME/.fzf
yes | $HOME/.fzf/install

# Install CCLS
[ -d "$HOME/ccls" ] && yes | rm -r $HOME/ccls
git clone --depth=1 --recursive https://github.com/MaskRay/ccls $HOME/ccls
cd $HOME/ccls
cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/bin
cmake --build Release
sudo cmake --build Release --target install
cd $HOME 
yes | rm -r $HOME/ccls

$SCRIPT_DIR/node-install
$SCRIPT_DIR/vim-install
$SCRIPT_DIR/tmux-install
$SCRIPT_DIR/network-tools-install
$SCRIPT_DIR/docker-install

sudo cp $SCRIPT_DIR/../tools/* /usr/local/bin/
cp $DOTFILES_DIR/.bashrc $HOME

$SCRIPT_DIR/dotfiles-install # Do this again to make sure dotfiles are propagated
source $HOME/.bashrc
