#!/bin/bash
set -e 

echo "Starting docker installation."
sleep 1

sudo apt update 

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common -y

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt update 
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

if grep -q docker /etc/group
then
  echo "docker group exists"
else
  echo "docker group does not exist"
  sudo groupadd docker
fi

sudo usermod -aG docker $USER
