#!/bin/bash
set -e

echo "Installing dotfiles."
sleep 1

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOTFILES_DIR=$SCRIPT_DIR/../dotfiles

mkdir -p $HOME/.vim
cp $DOTFILES_DIR/.vimrc $HOME
cp $DOTFILES_DIR/.tmux.conf $HOME
cp $DOTFILES_DIR/.bashrc $HOME
cp $DOTFILES_DIR/.bashrc_definitions $HOME
cp $DOTFILES_DIR/.bashrc_functions $HOME
