#!/bin/bash
DEVICE_NAME=/dev/ttyUSB0
FIRMWARE_LINK=https://micropython.org/resources/firmware/esp32-idf3-20210129-unstable-v1.13-291-gd1f120b14.bin

if [ -n "$1" ]
then
  DEVICE_NAME=$1
fi

echo "Install dependencies"
pip3 install esptool
pip3 install adafruit-ampy

echo "Downloading firmware"
tbin=$(mktemp)
wget $FIRMWARE_LINK -O $tbin

echo "Flashing firmware"
esptool.py --chip esp32 --port $DEVICE_NAME erase_flash
esptool.py --chip esp32 --port $DEVICE_NAME --baud 460800 write_flash -z 0x1000 $tbin

#echo "Flashing template files"
#sleep 2
#ampy --port $DEVICE_NAME put $(dirname $0)/boot.py
#ampy --port $DEVICE_NAME put $(dirname $0)/main.py



