#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TOOLS_DIR=$SCRIPT_DIR/../tools

echo 'Installing tool scripts..'
sudo cp $TOOLS_DIR/* /usr/local/bin/

