#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOTFILES_DIR=$SCRIPT_DIR/../dotfiles

echo "Installing Vim"
sudo apt update 

sudo apt install libncurses5 -y 
sudo apt install libncurses5-dev libncursesw5-dev -y 

cd /tmp && git clone https://github.com/vim/vim.git && cd /tmp/vim
./configure --enable-python3interp --prefix=/usr/local --with-python3-config-dir=/usr/lib/python3.6/config-*
make
sudo make install


echo "installing apt dependencies"
sudo apt install default-jdk -y
sudo apt install build-essential cmake python3-dev -y
sudo apt install python3-pip -y
sudo apt install flake8 -y
sudo apt install python3-pip -y
sudo apt install vim-gtk3 -y # For copying to system clipboard
sudo apt install clang-format -y
pip3 install --upgrade autopep8
pip3 install cmakelang
pip3 install doq

echo "dependencies installation complete"

echo "installing pip binaries"
sudo -H pip3 install pynvim

# Vim-Plug for plugin management
[ -d "$HOME/.vim" ] && yes | rm -r $HOME/.vim
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "vim-plug complete"

echo "installing vim plugins"
cp $SCRIPT_DIR/../dotfiles/.minimal_vimrc $HOME/.vimrc
/usr/bin/vim -c ':PlugInstall' -c ':qall' 
cp $SCRIPT_DIR/../dotfiles/.vimrc $HOME
echo "vim plugins complete"

echo "Installing Vim Completers"
cd $HOME/.vim/plugged/YouCompleteMe
python3 install.py --clang-completer --rust-completer
