#!/bin/bash
set -e
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
DOTFILES_DIR=$SCRIPT_DIR/../dotfiles

echo "vim installation"
sudo apt update 

echo "adding ppas and update"
sudo add-apt-repository ppa:jonathonf/vim -y
sudo apt update 

echo "installing apt binaries"
sudo apt install vim -y
sudo apt install vim-gtk -y
sudo apt install default-jdk -y
sudo apt install build-essential cmake python3-dev -y
echo "apt installation complete"

echo "installing pip binaries"
sudo -H pip3 install pynvim

# Vim-Plug for plugin management
[ -d "$HOME/.vim" ] && yes | rm -r $HOME/.vim
curl -fLo $HOME/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
echo "vim-plug complete"

echo "installing vim plugins"
cp $SCRIPT_DIR/../dotfiles/.minimal_vimrc $HOME/.vimrc
/usr/bin/vim -c ':PlugInstall' -c ':qall' 
cp $SCRIPT_DIR/../dotfiles/.vimrc $HOME
echo "vim plugins complete"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

