#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DIR=$SCRIPT_DIR/../config
DOTFILES_DIR=$SCRIPT_DIR/../dotfiles

echo -e "Installing dependencies.."
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer -y
sudo apt install tigervnc-scraping-server -y
echo -e "Set password"
vncpasswd

echo -e "Adding startup config file"
cp $CONFIG_DIR/xstartup ~/.vnc/
cp $DOTFILES_DIR/.xsessionrc ~

echo -e "Vncserver should be available now."

