#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DIR=$SCRIPT_DIR/../config

echo -e "Installing dependencies.."
sudo apt install tigervnc-standalone-server tigervnc-xorg-extension tigervnc-viewer -y
sudo apt install tigervnc-scraping-server -y

echo -e "Set password"
vncpasswd

echo -e "Adding startup config file for autologin"
cp $CONFIG_DIR/xstartup ~/.vnc/
sudo touch /etc/gdm3/custom.conf
sed ":%s/ubuntu/$USER/g" $CONFIG_DIR/custom.conf > /tmp/custom.conf
sudo cp /tmp/custom.conf /etc/gdm3

echo -e "Run VNC server on startup"
sudo touch /etc/systemd/system/x0vncserver.service
sed ":%s/ubuntu/$USER/g" $CONFIG_DIR/x0vncserver.service > /tmp/x0vncserver.service
sudo cp /tmp/x0vncserver.service /etc/systemd/system
sudo systemctl unmask x0vncserver.service
sudo systemctl enable x0vncserver.service
sudo systemctl start x0vncserver.service

echo -e "Vncserver should be available now."

journalctl -u x0vncserver.service -f

