#!/bin/bash
set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DIR=$SCRIPT_DIR/../config

echo "Installing X11VNC Server for Gnome Environments"
sudo apt install x11vnc -y

echo "Set no password for the VNC Server"
x11vnc -storepasswd "" $HOME/.x11vnc.pass

echo "Adding startup config file for autologin"
cp $CONFIG_DIR/xstartup ~/.vnc/
sudo touch /etc/gdm3/custom.conf
sed ":%s/ubuntu/$USER/g" $CONFIG_DIR/custom.conf > /tmp/custom.conf
sudo cp /tmp/custom.conf /etc/gdm3

echo "Configuring to run VNC server on startup"
sudo touch /etc/systemd/system/x11vnc.service
sudo cp $CONFIG_DIR/x11vnc.service /etc/systemd/system
sudo systemctl unmask x11vnc.service
sudo systemctl enable x11vnc.service
sudo systemctl start x11vnc.service

echo "X11VNC should be available now."

echo "To set x11vnc password:"
echo "x11vnc -storepasswd [yourpassword] $HOME/.x11vnc.pass"
sleep 1

echo "If using Raspberry Pi, edit config.txt with the following."
echo "This allows X server to start without plugging in a monitor."
echo "hdmi_force_hotplug=1 hdmi_drive=2 hdmi_mode=82"
echo "Visit here for more options: https://www.raspberrypi.org/documentation/configuration/config-txt/"

journalctl -u x11vnc.service -f

