#!/bin/bash

bt-pane() {

session=bt
tmux new-session -d -x "$(tput cols)" -y "$(tput lines)" -s $session || exit

# Configuring panes to use the current terminals resolution
WW=$(tmux display -p '#{window_width}')
WH=$(tmux display -p '#{window_height}')

WL=$(expr $WW \* 7 / 10)  # Amount to resize to the left
WR=$(expr $WW \* 3 / 10)  # Amount to resize to the right
WU=$(expr $WH \* 8 / 10)  # Amount to resize to the top
WD=$(expr $WH \* 2 / 10)  # Amount to resize to the bottom

tmux rename-window -t $session:0 main
tmux select-pane -t $session:main.0

tmux split-pane -t $session:main.0 -v
tmux split-pane -t $session:main.0 -h
tmux resize-pane -t $session:main.1 -x $WR
tmux resize-pane -t $session:main.2 -y $WD
tmux split-pane -t $session:main.1 -v
tmux split-pane -t $session:main.3 -h
tmux send-keys -t $session:main.0 'bluetoothctl' ENTER
tmux send-keys -t $session:main.1 'watch sudo hciconfig -a' ENTER
tmux send-keys -t $session:main.2 'watch sudo rfkill list' ENTER
tmux send-keys -t $session:main.3 'journalctl -e -u bluetooth.service -f' ENTER
tmux send-keys -t $session:main.4 'sudo systemctl restart bluetooth.service' 

tmux new-window -t $session:1 -n dbus
tmux select-pane -t $session:dbus.0
tmux send-keys -t $session:dbus.0 'TARGET_BT_DEVICE=hci0; gdbus introspect -y -d "org.bluez" -o "/org/bluez/$TARGET_BT_DEVICE"' 

if [[ ! "$TMUX" ]]; then
  tmux attach-session -t $session:main.0
else
  tmux switch -t $session:main.0
fi

}

export -f bt-pane
bt-pane
