#!/bin/bash
set -e

## Configure GRUB to boot in console mode or GUI mode
configure-boot-to-console() {
    if [ "$1" != 'console' ] && [  "$1" != 'gui' ]
    then
        echo "Enter 'console' or 'gui' to boot in the corresponding mode"
        return
    fi

    echo 'installing dependencies'    
    sudo apt install grub2-common -y
    sudo apt install resolvconf -y

    'adding and backing up grub file to /etc/default/grub.bak'
    sudo touch /etc/default/grub
    sudo cp /etc/default/grub /etc/default/grub.bak

    echo 'replacing required lines'
    sudo sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
    sudo sed -i '/GRUB_TERMINAL/d' /etc/default/grub

    if [ "$1" == 'console' ]
    then
        sudo sh -c 'echo "GRUB_CMDLINE_LINUX_DEFAULT=text" >> /etc/default/grub'
        sudo sh -c 'echo "GRUB_TERMINAL=console" >> /etc/default/grub'
        sudo update-grub

        echo 'enabling multi-user.targets for console mode'
        sudo systemctl enable multi-user.target --force
        sudo systemctl set-default multi-user.target
    elif  [ "$1" == 'gui' ]
        then
            sudo sh -c 'echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"" >> /etc/default/grub'
            echo 'enabling graphical.target for gui mode'
            sudo systemctl enable graphical.target --force
            sudo systemctl set-default graphical.target 
    fi

    echo "$1 mode on next reboot."
}

export -f configure-boot-to-console

configure-boot-to-console $1
