#!/bin/bash

## Configure GRUB to boot in console mode or GUI mode
configure-power-management() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to set power management accordingly."
        return
    fi

    if [ $1 == 'on' ]
    then
        sudo sed -i s/wifi.powersave\ =\ ./wifi.powersave\ =\ 2/ /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf

    elif [ $1 == 'off' ]
    then
        sudo sed -i s/wifi.powersave\ =\ ./wifi.powersave\ =\ 3/ /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
    fi

}

export -f configure-power-management
configure-power-management $1
