#!/bin/bash

dev-pane() {

session=develop
tmux new-session -d -s $session || exit

tmux rename-window -t $session:0 dev-pane
tmux select-pane -t $session:dev-pane.0

tmux split-pane -t $session:dev-pane.0 -h
tmux send -t $session:dev-pane.0 'tmux resize-pane -x 235 && clear' ENTER

tmux split-pane -t $session:dev-pane.0 -v
tmux send -t $session:dev-pane.0 'tmux resize-pane -y 65 && clear' ENTER

tmux split-pane -t $session:dev-pane.1 -h

if [[ ! "$TMUX" ]]; then
  tmux attach-session -t $session:dev-pane.0
else
  tmux switch -t $session:dev-pane.0
fi

}

export -f dev-pane
dev-pane
