#!/bin/bash

if [ -z "$1" ]
then
      echo "Enter a path as parameter."
      echo "Searches the given path in FZF for a file, and copies that file path to clipboard."
      exit
fi

(find -L $1 | fzf) | xclip -sel c

