#!/bin/bash

# fzf from a specified directory
function fz(){
    if [[ -z "$1" ]]; then
        fzf
        return
    fi
    find -L $1 2>&1 | grep -v "Permission denied" | fzf
}

if [ $# -lt 1 ]; then
    echo "fzcmd [cmd] [path]*"
    echo "runs the specified command on some file specified by FZF search in the given path."
    echo "if [n] parameters are required for give cmd, [n] paths are to be provided"
    exit
else
    fzargs=""
    for t in "${@:2}"; do
        fzargs=$fzargs" \$(fz $t)"
    done
    cmd="$1 $fzargs"
    eval $cmd
fi
