#!/bin/bash

function fzgrep() {

    if [ -z "$1" ]
    then
          echo "Usage: fzgrep [path-to-search]"
          echo "This will use FZF to search for a term within files in [path-to-search], and open to the selected line in vim"
          return 
    fi

    out=$(grep -rnw . -e "$1" | fzf)
    if [[ -z "$out" ]]; then
        return

    else
        target_file=$(echo $out | cut -d':' -f1)
        target_line=$(echo $out | cut -d':' -f2)
        vim +$target_line $target_file
    fi

}


export -f fzgrep
fzgrep $1
