#!/bin/bash

set -e 

if [ $# -eq 0 ]
  then
    echo "Supply email!"
    exit 1
fi

sudo apt-get install xclip -y
ssh-keygen -t rsa -b 4096 -C $1
eval "$(ssh-agent -s)"
ssh-add ~/.ssh/id_rsa
xclip -sel clip < ~/.ssh/id_rsa.pub