#!/bin/bash

CURRENT_SCRIPT_DIR_BASH_ONLY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CURRENT_SCRIPT_DIR_POSIX="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

echo "relative path of script"
echo $0
echo "directory name only"
echo ${PWD##*/}
echo "relative path of directory"
echo $(dirname "$0")
echo "current script dir, BASH ONLY"
echo $CURRENT_SCRIPT_DIR_BASH_ONLY
echo "current script dir, POSIX"
echo $CURRENT_SCRIPT_DIR_POSIX

