#!/bin/bash

for f in *; do
    if [ -d "$f" ] && [ -d "$f/.git" ] ; then
        cd $f
        echo -e "\033[36m$f:\033[0m" 
        echo "$f:"
        echo -n "branch:"
        git rev-parse --abbrev-ref HEAD
        echo -n "hash:"
        git rev-parse HEAD
        echo -n "status:"
        git status
        cd ..
        echo ""
    fi
done
