#!/bin/bash
set -e

netplan-reload() {

    sudoedit /etc/netplan/*
    clear
    
    echo "Reloading Netplan.."
    sudo systemctl daemon-reload
    sudo netplan generate --debug
    sudo netplan apply
    sudo systemctl daemon-reload

    echo "Unblocking wireless devices.."
    sudo rfkill unblock all

    clear
    journalctl -u systemd-networkd -f

}

export -f netplan-reload
netplan-reload
