#!/bin/bash

run-on-file-update() {

    echo "Runs the given command each time the given file is written to."

    if [ -z "$1" ]
      then
        echo "Enter path of file to watch as parameter 1."
    fi

    if [ -z "$2" ]
      then
        echo "Enter command to execute as parameter 2."
        exit
    fi

    echo "executing $2 on saving of $1"

    if [ -f $1 ]; then
        echo "file was provided."
        
        while :
        do
          inotifywait -q -e close_write $1 | eval $2
        done

    elif [ -d $1 ]; then
        echo "directory was provided."

        while :
        do
          inotifywait -q -e close_write -r -m $1 | eval $2
        done

    else 
        echo "$1 is not a directory or a file."
    fi

}

export -f run-on-file-update

run-on-file-update "$1" "$2"
