#!/bin/bash

function sshfs-mount-at()
{

if [ -z "$1" ]
  then
    echo "Specify remote to mount."
    exit
fi

if [ -z "$2" ]
  then
    echo "Specify mount point."
    exit
fi

if [[ ! -d "$2" ]]
then
    sudo mkdir $2
fi

sudo umount $2 &> /dev/null || true
sudo sshfs -o allow_other,default_permissions $1 $2
export MNT_HOME=$2

}

export -f sshfs-mount-at
sshfs-mount-at $1 $2
