#!/bin/bash
set -e

tb-conf-interface-forwarding() {
  echo "Forwards packets between two network interfaces, making this device act like a router."

  if [ "$1" != 'reset' ] && [ "$1" != 'enable' ]; then
    echo "Usage: tb-conf-interface-forwarding [reset|enable] [iface-1] [iface-2]"
    return
  fi

  if [ $1 == 'enable' ] && [ -z $3 ]; then
    echo "Usage: tb-conf-interface-forwarding [reset|enable] [iface-1] [iface-2]"
    return
  fi

  if [ $1 == 'enable' ]; then
    echo "Forwarding packets between $2 and $3"
    sudo sed -i s/\#*net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf
    sudo sysctl -w net.ipv4.ip_forward=1
    sudo iptables -A FORWARD -i $2 -o $3 -j ACCEPT
    sudo iptables -A FORWARD -i $3 -o $2 -j ACCEPT
    sudo iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
    sudo iptables -t nat -A POSTROUTING -o $3 -j MASQUERADE

  elif [ $1 == 'reset' ]; then
    echo "Reset routing tables to defaults."
    sudo sed -i s/\#*net.ipv4.ip_forward=1/\#net.ipv4.ip_forward=1/ /etc/sysctl.conf
    sudo sysctl -w net.ipv4.ip_forward=0

    sudo iptables -P INPUT ACCEPT
    sudo iptables -P OUTPUT ACCEPT
    sudo iptables -P FORWARD ACCEPT
    sudo iptables -F
  fi

  sudo sysctl -p

  echo "Current iptable Configuration"
  sudo iptables -S
  echo "Saving iptable configuration"
  sudo netfilter-persistent save
}

export -f tb-conf-interface-forwarding
tb-conf-interface-forwarding $1 $2 $3
