#!/bin/bash
set -e

tb-conf-boot-interface() {

  echo "Configures if Linux boots with or without X Server ( GUI )"

  if [[ "$1" != 'console' ]] && [[ "$1" != 'gui' ]]; then
    echo "Usage: tb-conf-boot-interface [console|gui]"
    return
  fi

  echo 'Installing required dependencies.'
  sudo apt install grub2-common -y
  sudo apt install resolvconf -y

  echo 'Adding and backing up grub file to /etc/default/grub.bak'
  sudo touch /etc/default/grub
  sudo touch /etc/default/grub.bak
  sudo cp /etc/default/grub /etc/default/grub.bak

  echo 'Removing configuration lines'
  sudo sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/d' /etc/default/grub
  sudo sed -i '/GRUB_TERMINAL/d' /etc/default/grub

  if [ "$1" == 'console' ]; then

    echo "Configuring to boot without X Server ( console )"
    sudo sh -c 'echo "GRUB_CMDLINE_LINUX_DEFAULT=text" >> /etc/default/grub'
    sudo sh -c 'echo "GRUB_TERMINAL=console" >> /etc/default/grub'
    sudo update-grub

    sudo systemctl enable multi-user.target --force
    sudo systemctl set-default multi-user.target

  elif [ "$1" == 'gui' ]; then
    echo "Configuring to boot with X Server ( GUI )"
    sudo sh -c 'echo "GRUB_CMDLINE_LINUX_DEFAULT=\"quiet splash\"" >> /etc/default/grub'
    sudo systemctl enable graphical.target --force
    sudo systemctl set-default graphical.target
  fi

  echo "Success."
  echo "$1 mode on next reboot."
}

export -f tb-conf-boot-interface

tb-conf-boot-interface $1
