#!/bin/bash
set -e

tb-sshfs-mount() {

  if [ -z "$1" ]; then
    echo "Usage: tb-sshfs-mount [remote] [mount point]"
    echo "Specify remote to mount."
    exit
  fi

  if [ -z "$2" ]; then
    echo "Usage: tb-sshfs-mount [remote] [mount point]"
    echo "Specify mount point."
    exit
  fi

  if [[ ! -d "$2" ]]; then
    sudo mkdir $2
  fi

  sudo umount $2 &>/dev/null || true
  sudo sshfs -o allow_other,default_permissions $1 $2
  export MNT_HOME=$2
  echo "You can find the path to device under environment variable MNT_HOME"
  ls $MNT_HOME

}

export -f tb-sshfs-mount
tb-sshfs-mount $1 $2
