#!/bin/bash
set -e

tb-test-trigger() {

    # PARENT_COMMAND=$(ps -o comm=$PPID)
    # PARENT_COMMAND=$(ps -o args=$PPID) # More detail

    # MSG="Triggered by $PARENT_COMMAND at `/usr/bin/date `"
    MSG="Triggered at `/usr/bin/date `"

    echo $MSG

    OUTFILE=$1
    if [ -z $OUTFILE ]
    then 
        OUTFILE='/tmp/test-trigger.log'
    fi
	    
    echo "Appending to $OUTFILE"
    touch $OUTFILE
    echo $MSG >> $OUTFILE

}

export -f tb-test-trigger
tb-test-trigger $1
