#!/bin/bash
set -e

tb-toggle-vnc-server-on-startup() {
  echo "Configurations to start up VNC Server on boot."

  if [ "$1" != 'disable' ] && [ "$1" != 'enable' ]; then
    echo "Usage: tb-toggle-vnc-server-on-startup [disable|enable]"
    return
  fi

  if [ $1 == 'enable' ]; then
    echo "Enabling VNC server on boot."
    echo "You can find a template x0vncserver.service in software-toolbox/config."
    sleep 1

    sudoedit /etc/systemd/system/x0vncserver.service
    sudo systemctl unmask x0vncserver.service
    sudo systemctl enable x0vncserver.service
    sudo systemctl start x0vncserver.service
    echo -e "Remember to also activate auto-login in order for X0 Server to start automatically."

  elif [ $1 == 'off' ]; then
    echo "Disabling VNC server on boot."
    sudo systemctl disable x0vncserver.service
    sudo systemctl stop x0vncserver.service
  fi
}

export -f tb-toggle-vnc-server-on-startup
b-toggle-vnc-server-on-startup $1
