#!/bin/bash
set -e

## Configure GRUB to boot in console mode or GUI mode
toggle-temp-swap-space() {
    ## https://linuxize.com/post/create-a-linux-swap-file/

    if [ "$1" != 'add' ] && [  "$1" != 'remove' ]
    then
        echo "Enter 'add' or 'remove' to temporarily add / remove X GB of swap space in /temp_swap."
        return
    fi

    if [ "$1" == 'add' ] && [ -z $2 ] 
    then
        echo "Enter number of GB of swap space to use."
        return
    fi

    if [ "$1" == 'add' ]  
    then
        sudo fallocate -l $2G /temp_swap
        sudo chmod 600 /temp_swap
        sudo mkswap /temp_swap
        sudo swapon /temp_swap
        echo "Added $2GB of swap space in /temp_swap."
        echo "Run sudo sysctl vm.swappiness=[1-100] to change swappiness value"
        echo "To make the change permanent open the /etc/fstab file and add /temp_swap swap swap defaults 0 0"
        free -m
        return
    elif [ "$1" == 'remove' ]
    then
        sudo swapoff -v /temp_swap
        sudo rm /temp_swap
        free -m
        return
    fi


}

export -f toggle-temp-swap-space

toggle-temp-swap-space $1 $2
