#!/bin/bash

toggle-ip-forwarding() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to ip forwarding accordingly."
        return
    fi

    if [ $1 == 'on' ]
    then
        sudo sed -i s/\#*net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf

    elif [ $1 == 'off' ]
    then
        sudo sed -i s/\#*net.ipv4.ip_forward=1/\#net.ipv4.ip_forward=1/ /etc/sysctl.conf
    fi
}

export -f toggle-ip-forwarding
toggle-ip-forwarding $1
