#!/bin/bash

toggle-hostapd-ap() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to set AP accordingly."
        return
    fi

    if [ $1 == 'on' ]
    then
        sudo rfkill unblock all
        sudo systemctl unmask hostapd.service
        sudo systemctl start hostapd.service

    elif [ $1 == 'off' ]
    then
        sudo systemctl stop hostapd.service
        sudo systemctl mask hostapd.service
    fi

    sudo systemctl status hostapd.service
}

export -f toggle-hostapd-ap
toggle-hostapd-ap $1
