#!/bin/bash
set -e

toggle-routing() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to ip routing accordingly."
        return
    fi

    if [ $1 == 'on' ] && [ -z $3 ]
    then
        echo "Enter the network interfaces to do NAT with."
        return
    fi

    if [ $1 == 'on' ]
    then
        sudo sed -i s/\#*net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/ /etc/sysctl.conf
        sudo sysctl -w net.ipv4.ip_forward=1
        sudo iptables -A FORWARD -i $2 -o $3 -j ACCEPT
        sudo iptables -A FORWARD -i $3 -o $2 -j ACCEPT
        sudo iptables -t nat -A POSTROUTING -o $2 -j MASQUERADE
        sudo iptables -t nat -A POSTROUTING -o $3 -j MASQUERADE

    elif [ $1 == 'off' ]
    then
        sudo sed -i s/\#*net.ipv4.ip_forward=1/\#net.ipv4.ip_forward=1/ /etc/sysctl.conf
        sudo sysctl -w net.ipv4.ip_forward=0

        sudo iptables -P INPUT ACCEPT
        sudo iptables -P OUTPUT ACCEPT
        sudo iptables -P FORWARD ACCEPT
        sudo iptables -F
    fi

    sudo sysctl -p

    echo 'current iptables:'
    sudo iptables -S
    sudo netfilter-persistent save
}


export -f toggle-routing
toggle-routing $1 $2 $3
