#!/bin/bash

while true; do
    read -p "Turn [off] or [on] power management? " yn
    case $yn in
        [off]* ) sudo sed -i s/wifi.powersave\ =\ ./wifi.powersave\ =\ 2/ /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf;  break;;
        [on]* ) sudo sed -i s/wifi.powersave\ =\ ./wifi.powersave\ =\ 3/ /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf; break;;
        * ) echo "Please answer off or on ";;
    esac
done

