#!/bin/bash
set -e

TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DIR=$TOOLS_DIR/../config

toggle-autologin-gnome() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to toggle autologin for gnome environments."
        return
    fi

    if [ $1 == 'on' ]
    then
      sudo sed -i '/AutomaticLoginEnable = true/s/^#*//g' /etc/gdm3/custom.conf 
      sudo sed -i "s/.*AutomaticLogin = .*/  AutomaticLogin = $USER/g" /etc/gdm3/custom.conf 

    elif [ $1 == 'off' ]
    then
      sudo sed -i '/AutomaticLoginEnable = true/s/^#*/#/g' /etc/gdm3/custom.conf
      sudo sed -i '/AutomaticLogin = /s/^#*/#/g' /etc/gdm3/custom.conf
    fi

    sed ":%s/ubuntu/$USER/g" /etc/gdm3/custom.conf > /tmp/custom.conf
    sudo cp /tmp/custom.conf /etc/gdm3
}

export -f toggle-autologin-gnome
toggle-autologin-gnome $1
