#!/bin/bash
set -e

toggle-dnsmasq() {
    if [ "$1" != 'off' ] && [  "$1" != 'on' ]
    then
        echo "Enter 'off' or 'on' to set dnsmasq accordingly."
        return
    fi

    if [ $1 == 'on' ]
    then
        sudo systemctl disable systemd-resolved.service
        sudo systemctl stop systemd-resolved.service
        sudo systemctl mask systemd-resolved.service
        sudo rfkill unblock all
        sudo systemctl unmask dnsmasq.service 
        sudo systemctl enable dnsmasq.service 
        sudo systemctl start dnsmasq.service

    elif [ $1 == 'off' ]
    then
        sudo systemctl disable dnsmasq.service
        sudo systemctl stop dnsmasq.service
        sudo systemctl mask dnsmasq.service
        sudo rfkill unblock all
        sudo systemctl unmask systemd-resolved.service 
        sudo systemctl enable systemd-resolved.service 
        sudo systemctl start systemd-resolved.service
    fi

    sudo systemctl status dnsmasq.service
}

export -f toggle-dnsmasq
toggle-dnsmasq $1
