network:
  version: 2
  renderer: networkd
  wifis:
    wl0:
      access-points:
        "SSID":
          password: "passwd"

        # For unsecured network
        # opennetwork_SSID: {}
      dhcp4: yes
