name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Environment
      run: $GITHUB_WORKSPACE/setup/dev-install
